### ISSUE TITLE
Quick start doesn't really work

### ISSUE THREAD

**Issue by nazar-pc** [latticexyz/mud#358]
Running this in an empty directory:
```
> npx @latticexyz/cli create mmm
Need to install the following packages:
  @latticexyz/cli
Ok to proceed? (y) 
npm WARN tarball tarball data for ds-test@git+https://github.com/dapphub/ds-test.git#9310e879db8ba3ea6d5c6489a579118fd264a3f5 (null) seems to be corrupted. Trying again.
npm WARN tarball tarball data for forge-std@git+https://github.com/foundry-rs/forge-std.git#6b4ca42943f093642bac31783b08aa52a5a6ff64 (null) seems to be corrupted. Trying again.
npm WARN tarball tarball data for ds-test@git+https://github.com/dapphub/ds-test.git#9310e879db8ba3ea6d5c6489a579118fd264a3f5 (null) seems to be corrupted. Trying again.
npm WARN tarball tarball data for forge-std@git+https://github.com/foundry-rs/forge-std.git#6b4ca42943f093642bac31783b08aa52a5a6ff64 (null) seems to be corrupted. Trying again.
npm WARN tarball tarball data for ds-test@git+https://github.com/dapphub/ds-test.git#c7a36fb236f298e04edf28e2fee385b80f53945f (null) seems to be corrupted. Trying again.
npm WARN tarball tarball data for ds-test@git+https://github.com/dapphub/ds-test.git#c7a36fb236f298e04edf28e2fee385b80f53945f (null) seems to be corrupted. Trying again.
npm WARN tarball tarball data for forge-std@git+https://github.com/foundry-rs/forge-std.git#37a3fe48c3a4d8239cda93445f0b5e76b1507436 (null) seems to be corrupted. Trying again.
npm WARN tarball tarball data for forge-std@git+https://github.com/foundry-rs/forge-std.git#37a3fe48c3a4d8239cda93445f0b5e76b1507436 (null) seems to be corrupted. Trying again.
npm WARN tarball tarball data for memmove@git+https://github.com/brockelmore/memmove.git#d577ecd1bc43656f4032edf4daa9797f756a8ad2 (null) seems to be corrupted. Trying again.
npm WARN tarball tarball data for memmove@git+https://github.com/brockelmore/memmove.git#d577ecd1bc43656f4032edf4daa9797f756a8ad2 (null) seems to be corrupted. Trying again.
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @latticexyz/solecs@1.33.1
npm WARN Found: ds-test@undefined
npm WARN node_modules/ds-test
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer ds-test@"https://github.com/dapphub/ds-test.git#c7a36fb236f298e04edf28e2fee385b80f53945f" from @latticexyz/solecs@1.33.1
npm WARN node_modules/@latticexyz/solecs
npm WARN   @latticexyz/solecs@"^1.33.1" from @latticexyz/cli@1.33.1
npm WARN   node_modules/@latticexyz/cli
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @latticexyz/solecs@1.33.1
npm WARN Found: forge-std@undefined
npm WARN node_modules/forge-std
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer forge-std@"https://github.com/foundry-rs/forge-std.git#37a3fe48c3a4d8239cda93445f0b5e76b1507436" from @latticexyz/solecs@1.33.1
npm WARN node_modules/@latticexyz/solecs
npm WARN   @latticexyz/solecs@"^1.33.1" from @latticexyz/cli@1.33.1
npm WARN   node_modules/@latticexyz/cli
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @latticexyz/solecs@1.33.1
npm WARN Found: memmove@undefined
npm WARN node_modules/memmove
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer memmove@"https://github.com/brockelmore/memmove.git#d577ecd1bc43656f4032edf4daa9797f756a8ad2" from @latticexyz/solecs@1.33.1
npm WARN node_modules/@latticexyz/solecs
npm WARN   @latticexyz/solecs@"^1.33.1" from @latticexyz/cli@1.33.1
npm WARN   node_modules/@latticexyz/cli
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /home/nazar-pc/.npm/_cacache/tmp/git-cloneDw2u84/package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/home/nazar-pc/.npm/_cacache/tmp/git-cloneDw2u84/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/nazar-pc/.npm/_logs/2023-01-27T14_40_01_845Z-debug.log
Exit code 254
```

I see some of the failed commits do exist, no idea what is happening here, but it is a bit frustrating.

```
> node --version
v18.13.0
> npm --version
7.24.2
```

**Comment by holic** [comment]
This should be fixed once the next release goes out cc @alvrs

**Comment by nazar-pc** [comment]
Is it already in the `main` branch so I can try to use it from GitHub?

**Comment by nazar-pc** [comment]
Hm, upgrading npm to `9.4.0` fixed the problem, though I'm still getting errors towards the end:

<details>

```
Creating new mud project in mmm
Cmd:
git clone https://github.com/latticexyz/mud-template-minimal mmm
Клонування в «mmm»...
remote: Enumerating objects: 136, done.
remote: Counting objects: 100% (136/136), done.
remote: Compressing objects: 100% (84/84), done.
remote: Total 136 (delta 53), reused 114 (delta 36), pack-reused 0
Отримання об’єктів: 100% (136/136), 99.34 KiB | 1.42 MiB/s, виконано.
Обробка відмінностей: 100% (53/53), виконано.
Installing dependencies...
Cmd:
yarn --cwd ./mmm
yarn install v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning "workspace-aggregator-f9570c44-67ba-439f-bf47-f616d5321dd2 > client > @improbable-eng/grpc-web@0.15.0" has unmet peer dependency "google-protobuf@^3.14.0".
warning "workspace-aggregator-f9570c44-67ba-439f-bf47-f616d5321dd2 > client > @latticexyz/network@1.30.1" has unmet peer dependency "@ethersproject/providers@^5.6.1".
warning "workspace-aggregator-f9570c44-67ba-439f-bf47-f616d5321dd2 > client > @latticexyz/network@1.30.1" has unmet peer dependency "@latticexyz/solecs@^1.28.1".
warning "workspace-aggregator-f9570c44-67ba-439f-bf47-f616d5321dd2 > client > @latticexyz/network@1.30.1" has unmet peer dependency "@latticexyz/utils@^1.28.1".
warning "workspace-aggregator-f9570c44-67ba-439f-bf47-f616d5321dd2 > client > @latticexyz/network@1.30.1" has unmet peer dependency "@protobuf-ts/grpcweb-transport@^2.7.0".
warning "workspace-aggregator-f9570c44-67ba-439f-bf47-f616d5321dd2 > client > @latticexyz/network@1.30.1" has incorrect peer dependency "async-mutex@^0.3.2".
warning "workspace-aggregator-f9570c44-67ba-439f-bf47-f616d5321dd2 > client > @latticexyz/network@1.30.1" has unmet peer dependency "observable-webworker@^4.0.1".
warning "workspace-aggregator-f9570c44-67ba-439f-bf47-f616d5321dd2 > client > @latticexyz/network@1.30.1" has unmet peer dependency "rxjs@^7.5.5".
warning "workspace-aggregator-f9570c44-67ba-439f-bf47-f616d5321dd2 > client > @latticexyz/recs@1.30.1" has unmet peer dependency "@latticexyz/utils@^1".
warning "workspace-aggregator-f9570c44-67ba-439f-bf47-f616d5321dd2 > client > @latticexyz/recs@1.30.1" has unmet peer dependency "rxjs@^7.5.5".
warning "workspace-aggregator-f9570c44-67ba-439f-bf47-f616d5321dd2 > client > @latticexyz/recs@1.30.1" has unmet peer dependency "type-fest@^2.14.0".
warning "workspace-aggregator-f9570c44-67ba-439f-bf47-f616d5321dd2 > client > @latticexyz/std-client@1.30.1" has unmet peer dependency "@latticexyz/solecs@^1.28.1".
warning "workspace-aggregator-f9570c44-67ba-439f-bf47-f616d5321dd2 > client > @latticexyz/std-client@1.30.1" has unmet peer dependency "@latticexyz/utils@^1.28.1".
warning "workspace-aggregator-f9570c44-67ba-439f-bf47-f616d5321dd2 > client > @latticexyz/std-client@1.30.1" has unmet peer dependency "lodash@^4.17.21".
warning "workspace-aggregator-f9570c44-67ba-439f-bf47-f616d5321dd2 > client > @latticexyz/std-client@1.30.1" has unmet peer dependency "phaser@3.60.0-beta.14".
warning "workspace-aggregator-f9570c44-67ba-439f-bf47-f616d5321dd2 > client > @latticexyz/std-client@1.30.1" has unmet peer dependency "react-collapse@^5.1.1".
warning "workspace-aggregator-f9570c44-67ba-439f-bf47-f616d5321dd2 > client > @latticexyz/std-client@1.30.1" has unmet peer dependency "react-dom@^18.2.0".
warning "workspace-aggregator-f9570c44-67ba-439f-bf47-f616d5321dd2 > client > @latticexyz/std-client@1.30.1" has unmet peer dependency "react-syntax-highlighter@^15.5.0".
warning "workspace-aggregator-f9570c44-67ba-439f-bf47-f616d5321dd2 > client > @latticexyz/std-client@1.30.1" has unmet peer dependency "rxjs@^7.5.5".
warning "workspace-aggregator-f9570c44-67ba-439f-bf47-f616d5321dd2 > contracts > @latticexyz/cli > @latticexyz/utils@1.30.1" has unmet peer dependency "mobx@^6.5.0".
warning "workspace-aggregator-f9570c44-67ba-439f-bf47-f616d5321dd2 > contracts > @latticexyz/cli > @latticexyz/utils@1.30.1" has unmet peer dependency "proxy-deep@^3.1.1".
warning "workspace-aggregator-f9570c44-67ba-439f-bf47-f616d5321dd2 > contracts > @latticexyz/cli > @latticexyz/utils@1.30.1" has unmet peer dependency "rxjs@^7.5.5".
warning "workspace-aggregator-f9570c44-67ba-439f-bf47-f616d5321dd2 > contracts > @latticexyz/cli > @latticexyz/utils@1.30.1" has unmet peer dependency "web3-utils@^1.8.0".
warning "workspace-aggregator-f9570c44-67ba-439f-bf47-f616d5321dd2 > contracts > @latticexyz/cli > @latticexyz/utils > typedoc-plugin-markdown@3.13.6" has unmet peer dependency "typedoc@>=0.23.0".
[4/4] Building fresh packages...
$ yarn workspace contracts prepare
yarn workspace v1.22.19
yarn run v1.22.19
$ mud types
Compiling contracts
Clearing forge build output directory ./out
Cmd:
forge build -o ./out
node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: spawn forge ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:476:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Emitted 'error' event on ChildProcess instance at:
    at ChildProcess._handle.onexit (node:internal/child_process:289:12)
    at onErrorNT (node:internal/child_process:476:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn forge',
  path: 'forge',
  spawnargs: [ 'build', '-o', './out' ]
}

Node.js v18.13.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
Exit code: 1
Command: /usr/bin/node
Arguments: /home/nazar-pc/node_modules/yarn/lib/cli.js prepare
Directory: /web/subspace/mmm/mmm/packages/contracts
Output:

info Visit https://yarnpkg.com/en/docs/cli/workspace for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

</details>

**Comment by mrhouzlane** [comment]
I also have an issue when running : 
`npx @latticexyz/cli create my-project`

node version : v18.8.0
npm version : 9.4.0 

Error : npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

**Comment by holic** [comment]
Try `yarn create mud my-project` and let us know if you have any issues?

**Comment by nazar-pc** [comment]
Gif at https://mud.dev/ still shows `npx mud create my-poroject` BTW
